### ISSUE TITLE
Support file download.

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaComputing/OpenAPI.jl#46]
It seems OpenAPI only support `application/json` response, since at this [code](https://github.com/JuliaComputing/OpenAPI.jl/blob/00fc01fc844e800ac8d0a8505ef9ead03279d96c/src/client.jl#L324) , response `Content-Type` set as `application/json` enforcement.

And I tried `application/zip` throws error

```
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _error(message::String, ps::JSON.Parser.MemoryParserState)
    @ JSON.Parser ~/.julia/packages/JSON/93Ea8/src/Parser.jl:140
  [3] parse_jsconstant(#unused#::JSON.Parser.ParserContext{Dict{String, Any}, Int64, true, nothing}, ps::JSON.Parser.MemoryParserState)
    @ JSON.Parser ~/.julia/packages/JSON/93Ea8/src/Parser.jl:193
  [4] parse_value(pc::JSON.Parser.ParserContext{Dict{String, Any}, Int64, true, nothing}, ps::JSON.Parser.MemoryParserState)
    @ JSON.Parser ~/.julia/packages/JSON/93Ea8/src/Parser.jl:170
  [5] parse(str::String; dicttype::Type, inttype::Type{Int64}, allownan::Bool, null::Nothing)
    @ JSON.Parser ~/.julia/packages/JSON/93Ea8/src/Parser.jl:450
  [6] parse
    @ ~/.julia/packages/JSON/93Ea8/src/Parser.jl:443 [inlined]
  [7] response
    @ ~/.julia/packages/OpenAPI/iZsIx/src/client.jl:330 [inlined]
  [8] response(#unused#::Type{Any}, resp::Downloads.Response, body::Vector{UInt8})
    @ OpenAPI.Clients ~/.julia/packages/OpenAPI/iZsIx/src/client.jl:325
  [9] exec(ctx::OpenAPI.Clients.Ctx, stream_to::Nothing)
    @ OpenAPI.Clients ~/.julia/packages/OpenAPI/iZsIx/src/client.jl:489
 [10] exec
    @ ~/.julia/packages/OpenAPI/iZsIx/src/client.jl:469 [inlined]
 [11] #datasets_download#61
    @ ~/Documents/github/Kaggle.jl/src/apis/api_KaggleApi.jl:490 [inlined]
 [12] datasets_download(_api::Main.Kaggle.APIClient.KaggleApi, owner_slug::String, dataset_slug::String)
    @ Main.Kaggle.APIClient ~/Documents/github/Kaggle.jl/src/apis/api_KaggleApi.jl:488
 [13] top-level scope
    @ ~/Documents/github/Kaggle.jl/src/Kaggle.jl:22
```

It parses the response body as json.

I want to make a PR to support file downloads. What do you think?

**Comment by Ellipse0934** [comment]
Please feel free to make a PR.

**Comment by Ellipse0934** [comment]
#25 may have addressed it. That should probably go in first. I'll try bumping it soon.

**Comment by tanmaykm** [comment]
#25 is about server responses, but from the issue description this feels like a client side need. And looks like the client [here](https://github.com/JuliaComputing/OpenAPI.jl/blob/00fc01fc844e800ac8d0a8505ef9ead03279d96c/src/client.jl#L324) should honor the content type if the server has sent one. It only defaults to json if there's no header.

@NeroBlackstone do you have a spec that you could point out which we could use to understand more about what's needed?

**Comment by NeroBlackstone** [comment]
I don't know much about OpenAPI specifications, I can only give some opinions on how to avoid this error.

1. If we have specified `MIME` in the response body at the API definition file, like:

``` yaml
 content:  # Response body
            application/json:  # Media type
              schema:
                $ref: '#/components/schemas/User'
```

Client should turn the response body to the corresponding `OpenAPI.APIModel` (specific julia struct).

And if return a file:

``` yaml
content:
            application/pdf:
              schema:
                type: string
                format: binary
```

Download this file. (Is this feature already implemented? Please tell me.)

2. If we do not specify `MIME` for the return object. (It could be happened in some swagger 2.0 API, like [kaggle](https://github.com/Kaggle/kaggle-api/blob/75dfa27d3c2886ea46e4d0c6bfcc0cc322af554b/KaggleSwagger.yaml#L276C13-L276C13)) We treat it as an undefined response. How to handle depending on the server response header `Content-Type`. 

For JSON, we just return a parsed Dict.
For text, we return a string.
For other file types, we download it.
(Is this compliant with OpenAPI Client implementation specification for handling such situations? Please tell me)

**Comment by NeroBlackstone** [comment]
We need to add a test for [file](https://swagger.io/docs/specification/data-models/data-types/#file) first. Ensure we can handle file download in OpenAPI 3.0 first. Then we deal with "undefined response", which the response body should convert by header `Content-Type`

### yaml
type: string
format: binary  # binary file contents

type: string
format: byte    # base64-encoded file contents
###

**Comment by NeroBlackstone** [comment]
Funny, seems a lot of work needs to be done. Obviously, file [upload](https://github.com/JuliaComputing/OpenAPI.jl/blob/00fc01fc844e800ac8d0a8505ef9ead03279d96c/test/client/petstore_v3/petstore_test_petapi.jl#L66) and download not work yet.

**Comment by NeroBlackstone** [comment]
Could you please give an example of how to use[ `response_stream` ](https://github.com/JuliaComputing/OpenAPI.jl#client-apis)to receive data?

**Comment by NeroBlackstone** [comment]
I make a PR for this problem. Now we can get the correct data for any 

But I have more thoughts.

For now, we can download file response use:

``` julia
result, http_response=datasets_download(api,"kapturovalexander","students-in-rooms")
open("a.zip","w") do file
    write(file,result)
end
```

Shall we need a more elegant way to download files if the response content-type is file?

What about generating a new function for every file content-type response? Like:

``` julia
datasets_download_save(path, api; param...)
    result, http_response=datasets_download(api,param...)
    file_name = # get file name for the header `Content-Disposition` field
    open("path/file_name","w") do file
        write(file,result)
    end
end
```

**Comment by NeroBlackstone** [comment]
I can make a same implementation as [here](https://github.com/Kaggle/kaggle-api/blob/75dfa27d3c2886ea46e4d0c6bfcc0cc322af554b/kaggle/api_client.py#L521).

**Comment by tanmaykm** [comment]
Seems like a good idea. But instead of generating it for every API, we could provide a generic method in OpenAPI.jl that does the same. Something like:

```julia
function downloadlocation(f, path)
    result, http_response = f()
    file_name = # get file name for the header `Content-Disposition` field
    file_path = joinpath(path, file_name)
    open(file_path,"w") do file
        write(file,result)
    end
    return result, http_response, file_path
end
```

So, one could use it like:

```julia
_result, _http_response, file_path = OpenAPI.downloadlocation(path) do
    datasets_download(api,"kapturovalexander","students-in-rooms")
end

@info("dataset stored at $file_path")
```
